language: node_js

node_js: 
  - "stable"

cache:
  directories:
    - "node_modules"

before_script:
 -  npm install && npm run migrate

script:
  - nyc --reporter=lcov npm test

after_success:
  - npm run coveralls
