language: node_js
node_js: 
  - "stable"
node:
  -NODE_ENV='development'
  -NODE_ENV='production';
cache:
  directories:
    - "node_modules"



# language: node_js
# node_js:
#   - stable
# install:
#   - npm install
# script:
#   - npm run test