language: node_js

node_js: 
  - "stable"

cache:
  directories:
    - "node_modules"

before_script:
 -  npm install

script:
  - nyc --reporter=lcov npm test
  - npm run migrate

after_success:
  - npm run coveralls

  